//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWP_SOA_VERITABANI.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cevaplar
    {
        public int cevapID { get; set; }
        public string cevapAdSoyad { get; set; }
        public string cevapMail { get; set; }
        public string cevapIcerik { get; set; }
        public Nullable<System.DateTime> cevapTarih { get; set; }
        public Nullable<bool> cevapOnay { get; set; }
        public string cevapResim { get; set; }
        public Nullable<int> soruID { get; set; }
    
        public virtual Sorular Sorular { get; set; }
    }
}
