//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWP_SOA_VERITABANI.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class iletisim
    {
        public int iletisimID { get; set; }
        public string iletisimAdSoyad { get; set; }
        public string iletisimMail { get; set; }
        public string iletisimIcerik { get; set; }
        public Nullable<System.DateTime> iletisimTarih { get; set; }
    }
}
