//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWP_SOA_VERITABANI.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategori()
        {
            this.Sorulars = new HashSet<Sorular>();
        }
    
        public int kategoriID { get; set; }
        public string kategoriAd { get; set; }
        public Nullable<int> kategoriSira { get; set; }
        public Nullable<int> kategoriAdet { get; set; }
        public string kategoriResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorular> Sorulars { get; set; }
    }
}
