//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWP_SOA_VERITABANI.SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yonetici
    {
        public int yoneticiID { get; set; }
        public string yoneticiAdSoyad { get; set; }
        public string yoneticiKullaniciAd { get; set; }
        public string yoneticiSifre { get; set; }
    }
}
